name: Deploy Nuxt 3 to GitHub Pages

on:
  push:
    branches:
      - main  # change if your default branch is different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # required to push to gh-pages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build & pre-render Nuxt
        run: npx nuxi generate

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.output/public
          cname: rjsoftwaresolutions.nl